package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Absences generated by hbm2java
 */
public class Absences implements java.io.Serializable {

	private String absenceId;
	private Users usersByUserIdchange;
	private Users usersByUserIdsend;
	private String absenceType;
	private String status;
	private Set managerreplytofcses = new HashSet(0);
	private Set shiftdetailses = new HashSet(0);

	public Absences() {
	}

	public Absences(String absenceId, Users usersByUserIdsend, String absenceType, String status) {
		this.absenceId = absenceId;
		this.usersByUserIdsend = usersByUserIdsend;
		this.absenceType = absenceType;
		this.status = status;
	}

	public Absences(String absenceId, Users usersByUserIdchange, Users usersByUserIdsend, String absenceType,
			String status, Set managerreplytofcses, Set shiftdetailses) {
		this.absenceId = absenceId;
		this.usersByUserIdchange = usersByUserIdchange;
		this.usersByUserIdsend = usersByUserIdsend;
		this.absenceType = absenceType;
		this.status = status;
		this.managerreplytofcses = managerreplytofcses;
		this.shiftdetailses = shiftdetailses;
	}

	public String getAbsenceId() {
		return this.absenceId;
	}

	public void setAbsenceId(String absenceId) {
		this.absenceId = absenceId;
	}

	public Users getUsersByUserIdchange() {
		return this.usersByUserIdchange;
	}

	public void setUsersByUserIdchange(Users usersByUserIdchange) {
		this.usersByUserIdchange = usersByUserIdchange;
	}

	public Users getUsersByUserIdsend() {
		return this.usersByUserIdsend;
	}

	public void setUsersByUserIdsend(Users usersByUserIdsend) {
		this.usersByUserIdsend = usersByUserIdsend;
	}

	public String getAbsenceType() {
		return this.absenceType;
	}

	public void setAbsenceType(String absenceType) {
		this.absenceType = absenceType;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set getManagerreplytofcses() {
		return this.managerreplytofcses;
	}

	public void setManagerreplytofcses(Set managerreplytofcses) {
		this.managerreplytofcses = managerreplytofcses;
	}

	public Set getShiftdetailses() {
		return this.shiftdetailses;
	}

	public void setShiftdetailses(Set shiftdetailses) {
		this.shiftdetailses = shiftdetailses;
	}

}
