package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Costumetype generated by hbm2java
 */
public class Costumetype implements java.io.Serializable {

	private Integer typeId;
	private String typename;
	private Set costumes = new HashSet(0);
	private Set costumes_1 = new HashSet(0);

	public Costumetype() {
	}

	public Costumetype(String typename) {
		this.typename = typename;
	}

	public Costumetype(String typename, Set costumes, Set costumes_1) {
		this.typename = typename;
		this.costumes = costumes;
		this.costumes_1 = costumes_1;
	}

	public Integer getTypeId() {
		return this.typeId;
	}

	public void setTypeId(Integer typeId) {
		this.typeId = typeId;
	}

	public String getTypename() {
		return this.typename;
	}

	public void setTypename(String typename) {
		this.typename = typename;
	}

	public Set getCostumes() {
		return this.costumes;
	}

	public void setCostumes(Set costumes) {
		this.costumes = costumes;
	}

	public Set getCostumes_1() {
		return this.costumes_1;
	}

	public void setCostumes_1(Set costumes_1) {
		this.costumes_1 = costumes_1;
	}

}
