package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * Fcdetails generated by hbm2java
 */
public class Fcdetails implements java.io.Serializable {

	private String fcDetailId;
	private Branches branches;
	private Users users;

	public Fcdetails() {
	}

	public Fcdetails(String fcDetailId, Branches branches, Users users) {
		this.fcDetailId = fcDetailId;
		this.branches = branches;
		this.users = users;
	}

	public String getFcDetailId() {
		return this.fcDetailId;
	}

	public void setFcDetailId(String fcDetailId) {
		this.fcDetailId = fcDetailId;
	}

	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
