package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * Managerreplytofcs generated by hbm2java
 */
public class Managerreplytofcs implements java.io.Serializable {

	private String replyId;
	private Absences absences;
	private Users users;
	private String status;

	public Managerreplytofcs() {
	}

	public Managerreplytofcs(String replyId, Absences absences, Users users, String status) {
		this.replyId = replyId;
		this.absences = absences;
		this.users = users;
		this.status = status;
	}

	public String getReplyId() {
		return this.replyId;
	}

	public void setReplyId(String replyId) {
		this.replyId = replyId;
	}

	public Absences getAbsences() {
		return this.absences;
	}

	public void setAbsences(Absences absences) {
		this.absences = absences;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
