package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * PmaDesignerSettings generated by hbm2java
 */
public class PmaDesignerSettings implements java.io.Serializable {

	private String username;
	private String settingsData;

	public PmaDesignerSettings() {
	}

	public PmaDesignerSettings(String username, String settingsData) {
		this.username = username;
		this.settingsData = settingsData;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getSettingsData() {
		return this.settingsData;
	}

	public void setSettingsData(String settingsData) {
		this.settingsData = settingsData;
	}

}
