package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * PmaNavigationhiding generated by hbm2java
 */
public class PmaNavigationhiding implements java.io.Serializable {

	private PmaNavigationhidingId id;

	public PmaNavigationhiding() {
	}

	public PmaNavigationhiding(PmaNavigationhidingId id) {
		this.id = id;
	}

	public PmaNavigationhidingId getId() {
		return this.id;
	}

	public void setId(PmaNavigationhidingId id) {
		this.id = id;
	}

}
