package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * PmaPdfPages generated by hbm2java
 */
public class PmaPdfPages implements java.io.Serializable {

	private Integer pageNr;
	private String dbName;
	private String pageDescr;

	public PmaPdfPages() {
	}

	public PmaPdfPages(String dbName, String pageDescr) {
		this.dbName = dbName;
		this.pageDescr = pageDescr;
	}

	public Integer getPageNr() {
		return this.pageNr;
	}

	public void setPageNr(Integer pageNr) {
		this.pageNr = pageNr;
	}

	public String getDbName() {
		return this.dbName;
	}

	public void setDbName(String dbName) {
		this.dbName = dbName;
	}

	public String getPageDescr() {
		return this.pageDescr;
	}

	public void setPageDescr(String pageDescr) {
		this.pageDescr = pageDescr;
	}

}
