package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * PmaTableInfo generated by hbm2java
 */
public class PmaTableInfo implements java.io.Serializable {

	private PmaTableInfoId id;
	private String displayField;

	public PmaTableInfo() {
	}

	public PmaTableInfo(PmaTableInfoId id, String displayField) {
		this.id = id;
		this.displayField = displayField;
	}

	public PmaTableInfoId getId() {
		return this.id;
	}

	public void setId(PmaTableInfoId id) {
		this.id = id;
	}

	public String getDisplayField() {
		return this.displayField;
	}

	public void setDisplayField(String displayField) {
		this.displayField = displayField;
	}

}
