package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * PmaUsers generated by hbm2java
 */
public class PmaUsers implements java.io.Serializable {

	private PmaUsersId id;

	public PmaUsers() {
	}

	public PmaUsers(PmaUsersId id) {
		this.id = id;
	}

	public PmaUsersId getId() {
		return this.id;
	}

	public void setId(PmaUsersId id) {
		this.id = id;
	}

}
