package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * PmaUsergroups generated by hbm2java
 */
public class PmaUsergroups implements java.io.Serializable {

	private PmaUsergroupsId id;

	public PmaUsergroups() {
	}

	public PmaUsergroups(PmaUsergroupsId id) {
		this.id = id;
	}

	public PmaUsergroupsId getId() {
		return this.id;
	}

	public void setId(PmaUsergroupsId id) {
		this.id = id;
	}

}
