package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schedules generated by hbm2java
 */
public class Schedules implements java.io.Serializable {

	private String scheduleId;
	private Date date;
	private Set shiftses = new HashSet(0);

	public Schedules() {
	}

	public Schedules(String scheduleId, Date date) {
		this.scheduleId = scheduleId;
		this.date = date;
	}

	public Schedules(String scheduleId, Date date, Set shiftses) {
		this.scheduleId = scheduleId;
		this.date = date;
		this.shiftses = shiftses;
	}

	public String getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Set getShiftses() {
		return this.shiftses;
	}

	public void setShiftses(Set shiftses) {
		this.shiftses = shiftses;
	}

}
