package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Shifts generated by hbm2java
 */
public class Shifts implements java.io.Serializable {

	private String shiftId;
	private Branches branches;
	private Typetimes typetimes;
	private Schedules schedules;
	private Set shiftdetailses = new HashSet(0);

	public Shifts() {
	}

	public Shifts(String shiftId, Branches branches, Typetimes typetimes, Schedules schedules) {
		this.shiftId = shiftId;
		this.branches = branches;
		this.typetimes = typetimes;
		this.schedules = schedules;
	}

	public Shifts(String shiftId, Branches branches, Typetimes typetimes, Schedules schedules, Set shiftdetailses) {
		this.shiftId = shiftId;
		this.branches = branches;
		this.typetimes = typetimes;
		this.schedules = schedules;
		this.shiftdetailses = shiftdetailses;
	}

	public String getShiftId() {
		return this.shiftId;
	}

	public void setShiftId(String shiftId) {
		this.shiftId = shiftId;
	}

	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	public Typetimes getTypetimes() {
		return this.typetimes;
	}

	public void setTypetimes(Typetimes typetimes) {
		this.typetimes = typetimes;
	}

	public Schedules getSchedules() {
		return this.schedules;
	}

	public void setSchedules(Schedules schedules) {
		this.schedules = schedules;
	}

	public Set getShiftdetailses() {
		return this.shiftdetailses;
	}

	public void setShiftdetailses(Set shiftdetailses) {
		this.shiftdetailses = shiftdetailses;
	}

}
