package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * Shiftdetails generated by hbm2java
 */
public class Shiftdetails implements java.io.Serializable {

	private String shiftDetailId;
	private Shifts shifts;
	private Absences absences;
	private Users users;
	private String status;
	private String statusCl;

	public Shiftdetails() {
	}

	public Shiftdetails(String shiftDetailId, Shifts shifts, Users users, String status, String statusCl) {
		this.shiftDetailId = shiftDetailId;
		this.shifts = shifts;
		this.users = users;
		this.status = status;
		this.statusCl = statusCl;
	}

	public Shiftdetails(String shiftDetailId, Shifts shifts, Absences absences, Users users, String status,
			String statusCl) {
		this.shiftDetailId = shiftDetailId;
		this.shifts = shifts;
		this.absences = absences;
		this.users = users;
		this.status = status;
		this.statusCl = statusCl;
	}

	public String getShiftDetailId() {
		return this.shiftDetailId;
	}

	public void setShiftDetailId(String shiftDetailId) {
		this.shiftDetailId = shiftDetailId;
	}

	public Shifts getShifts() {
		return this.shifts;
	}

	public void setShifts(Shifts shifts) {
		this.shifts = shifts;
	}

	public Absences getAbsences() {
		return this.absences;
	}

	public void setAbsences(Absences absences) {
		this.absences = absences;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatusCl() {
		return this.statusCl;
	}

	public void setStatusCl(String statusCl) {
		this.statusCl = statusCl;
	}

}
