package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Typeroles generated by hbm2java
 */
public class Typeroles implements java.io.Serializable {

	private String roleId;
	private String roleName;
	private Set userses = new HashSet(0);

	public Typeroles() {
	}

	public Typeroles(String roleId, String roleName) {
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public Typeroles(String roleId, String roleName, Set userses) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.userses = userses;
	}

	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set getUserses() {
		return this.userses;
	}

	public void setUserses(Set userses) {
		this.userses = userses;
	}

}
