package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Typetimes generated by hbm2java
 */
public class Typetimes implements java.io.Serializable {

	private String timeId;
	private Date timeStart;
	private Date timeEnd;
	private Set shiftses = new HashSet(0);

	public Typetimes() {
	}

	public Typetimes(String timeId, Date timeStart, Date timeEnd) {
		this.timeId = timeId;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
	}

	public Typetimes(String timeId, Date timeStart, Date timeEnd, Set shiftses) {
		this.timeId = timeId;
		this.timeStart = timeStart;
		this.timeEnd = timeEnd;
		this.shiftses = shiftses;
	}

	public String getTimeId() {
		return this.timeId;
	}

	public void setTimeId(String timeId) {
		this.timeId = timeId;
	}

	public Date getTimeStart() {
		return this.timeStart;
	}

	public void setTimeStart(Date timeStart) {
		this.timeStart = timeStart;
	}

	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

	public Set getShiftses() {
		return this.shiftses;
	}

	public void setShiftses(Set shiftses) {
		this.shiftses = shiftses;
	}

}
