package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Userrantal generated by hbm2java
 */
public class Userrantal implements java.io.Serializable {

	private Integer cusId;
	private String name;
	private String username;
	private String pwd;
	private String address;
	private String userRole;
	private Set rentalsForCusId = new HashSet(0);
	private Set rentalsForEmpId = new HashSet(0);

	public Userrantal() {
	}

	public Userrantal(String name, String username, String pwd, String address, String userRole, Set rentalsForCusId,
			Set rentalsForEmpId) {
		this.name = name;
		this.username = username;
		this.pwd = pwd;
		this.address = address;
		this.userRole = userRole;
		this.rentalsForCusId = rentalsForCusId;
		this.rentalsForEmpId = rentalsForEmpId;
	}

	public Integer getCusId() {
		return this.cusId;
	}

	public void setCusId(Integer cusId) {
		this.cusId = cusId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPwd() {
		return this.pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	public Set getRentalsForCusId() {
		return this.rentalsForCusId;
	}

	public void setRentalsForCusId(Set rentalsForCusId) {
		this.rentalsForCusId = rentalsForCusId;
	}

	public Set getRentalsForEmpId() {
		return this.rentalsForEmpId;
	}

	public void setRentalsForEmpId(Set rentalsForEmpId) {
		this.rentalsForEmpId = rentalsForEmpId;
	}

}
