package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private UserId id;

	public User() {
	}

	public User(UserId id) {
		this.id = id;
	}

	public UserId getId() {
		return this.id;
	}

	public void setId(UserId id) {
		this.id = id;
	}

}
