package com.example.model;
// Generated Mar 26, 2024, 9:45:28 AM by Hibernate Tools 3.6.2.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String userId;
	private Branches branches;
	private Typeroles typeroles;
	private String firstName;
	private String surName;
	private String email;
	private Date dateBirth;
	private String passwordUser;
	private Set shiftdetailses = new HashSet(0);
	private Set managerreplytofcses = new HashSet(0);
	private Set fcdetailses = new HashSet(0);
	private Set absencesesForUserIdsend = new HashSet(0);
	private Set absencesesForUserIdchange = new HashSet(0);

	public Users() {
	}

	public Users(String userId, Branches branches, Typeroles typeroles, String firstName, String surName, String email,
			Date dateBirth, String passwordUser) {
		this.userId = userId;
		this.branches = branches;
		this.typeroles = typeroles;
		this.firstName = firstName;
		this.surName = surName;
		this.email = email;
		this.dateBirth = dateBirth;
		this.passwordUser = passwordUser;
	}

	public Users(String userId, Branches branches, Typeroles typeroles, String firstName, String surName, String email,
			Date dateBirth, String passwordUser, Set shiftdetailses, Set managerreplytofcses, Set fcdetailses,
			Set absencesesForUserIdsend, Set absencesesForUserIdchange) {
		this.userId = userId;
		this.branches = branches;
		this.typeroles = typeroles;
		this.firstName = firstName;
		this.surName = surName;
		this.email = email;
		this.dateBirth = dateBirth;
		this.passwordUser = passwordUser;
		this.shiftdetailses = shiftdetailses;
		this.managerreplytofcses = managerreplytofcses;
		this.fcdetailses = fcdetailses;
		this.absencesesForUserIdsend = absencesesForUserIdsend;
		this.absencesesForUserIdchange = absencesesForUserIdchange;
	}

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public Branches getBranches() {
		return this.branches;
	}

	public void setBranches(Branches branches) {
		this.branches = branches;
	}

	public Typeroles getTyperoles() {
		return this.typeroles;
	}

	public void setTyperoles(Typeroles typeroles) {
		this.typeroles = typeroles;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getSurName() {
		return this.surName;
	}

	public void setSurName(String surName) {
		this.surName = surName;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getDateBirth() {
		return this.dateBirth;
	}

	public void setDateBirth(Date dateBirth) {
		this.dateBirth = dateBirth;
	}

	public String getPasswordUser() {
		return this.passwordUser;
	}

	public void setPasswordUser(String passwordUser) {
		this.passwordUser = passwordUser;
	}

	public Set getShiftdetailses() {
		return this.shiftdetailses;
	}

	public void setShiftdetailses(Set shiftdetailses) {
		this.shiftdetailses = shiftdetailses;
	}

	public Set getManagerreplytofcses() {
		return this.managerreplytofcses;
	}

	public void setManagerreplytofcses(Set managerreplytofcses) {
		this.managerreplytofcses = managerreplytofcses;
	}

	public Set getFcdetailses() {
		return this.fcdetailses;
	}

	public void setFcdetailses(Set fcdetailses) {
		this.fcdetailses = fcdetailses;
	}

	public Set getAbsencesesForUserIdsend() {
		return this.absencesesForUserIdsend;
	}

	public void setAbsencesesForUserIdsend(Set absencesesForUserIdsend) {
		this.absencesesForUserIdsend = absencesesForUserIdsend;
	}

	public Set getAbsencesesForUserIdchange() {
		return this.absencesesForUserIdchange;
	}

	public void setAbsencesesForUserIdchange(Set absencesesForUserIdchange) {
		this.absencesesForUserIdchange = absencesesForUserIdchange;
	}

}
